modal: 'img'
mode: 'train'
get_from_snapshot: False # 控制是否使用snapshot中的model
model_path:
  save: False # 是否需要保存模型
  snapshot_dir: "save_models"
  snapshot: "best_snapshot.pt"
split_dataset: True
split_test_ratio: 0.2
criterion: "CrossEntropyLoss" # 支持loss文件夹下所有的loss
optimizer: "AdamW" # 目前支持AdamW
scheduler:
  name: "constant"
  ratio: 0.1
metrics: "F1score_Precision_Recall" # F1score_Precision_Recall
main_metric: "Precision"
batch_size:
  train: 64
  eval: 64
max_epochs: 5
wd: 0.001
momentum: 0 # SGD优化器中可能用到
seed: 42
early_stop: 100
lr: 0.001
dropout: 0.0
extra:
  delta: 0.1
