modal: 'img'
get_from_snapshot: False
model_path:
  pretrained_model_dir: "pretrained_model"
  pretrained_model: "bert-base-uncased"
  tokenizer: "bert-base-uncased"
  save: False
  snapshot_dir: "save_models"
  snapshot: "best_snapshot.pt"
split_dataset: True
split_test_ratio: 0.2
data_path:
  data_dir: "data/VAST/"
  train: "vast_train.csv"
  eval: "vast_test.csv"
  predict: "vast_test.csv"
criterion: "CrossEntropyLoss" # DualLoss,FocalLoss
optimizer: "AdamW" # AdamW
scheduler:
  name: "constant"
  ratio: 0.1
metrics: "F1score_Precision_Recall" # F1score_Precision_Recall
main_metric: "F1score"
mode: 'train'
batch_size:
  train: 64
  eval: 64
max_epochs: 5
wd: 0.001
seed: 42
early_stop: 100
lr: 0.001
dropout: 0.0
