model_path:
  pretrained_model_dir: "pretrained_model"
  pretrained_model: "bert-base-uncased"
  tokenizer: "bert-base-uncased"
  save: False
  snapshot_dir: "save_models"
  snapshot: "best_snapshot.pt"
data_path:
  data_dir: "data/VAST/"
  train: "vast_train.csv"
  eval: "vast_test.csv"
  predict: "vast_test.csv"
criterion: "DualLoss"
optimizer: "AdamW"
scheduler:
  name: "constant"
  ratio: 0.1
metrics: "StanceVAST"
main_metric: "zero_avg"
mode: 'train'
batch_size:
  train: 64
  eval: 512
max_epochs: 100
wd: 0.001
seed: 42
early_stop: 100
lr: 0.00002
dropout: 0.0
StanceVAST:
  max_topic_length: 32
  max_text_length: 256
  cls_t: 50.0
  token_t: 15.0
  num_classes: 3
  max_text_length: 256
  cls_loss_weight: 0.2
